services:
  redis:
    image: ghcr.io/dragonflydb/dragonfly:v1.34.1
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  pas:
    pull_policy: always
    command: ["pas"]
    environment:
      PWB_CONSUMER_TOKEN: $CURATORBOT_PWB_CONSUMER_TOKEN
      PWB_CONSUMER_SECRET: $CURATORBOT_PWB_CONSUMER_SECRET
      PWB_ACCESS_TOKEN: $CURATORBOT_PWB_ACCESS_TOKEN
      PWB_ACCESS_SECRET: $CURATORBOT_PWB_ACCESS_SECRET
      PWB_USERNAME: $CURATORBOT_PWB_USERNAME
      FLICKR_API_KEY: $FLICKR_API_KEY
      TOOL_REDIS_URI: "redis://redis"
      EMAIL: $EMAIL
    image: tools-harbor.wmcloud.org/tool-curator/wikibots:latest
    restart: "always"
    # build: .
    # volumes:
    #   - ./src:/app/src
    depends_on:
      - redis

volumes:
  redis:
