[project]
name = "wikibots"
version = "0.1.0"
authors = [
    {name = "DaxServer",email = "daxserver@icloud.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pywikibot (>=10.0.0,<11.0.0)",
    "python-dateutil (>=2.9.0.post0,<3.0.0)",
    "deepdiff (>=8.4.2,<9.0.0)",
    "requests-oauthlib (>=2.0.0,<3.0.0)",
    "google-api-python-client (>=2.166.0,<3.0.0)",
    "flickr-photos-api (>=2.18.0,<3.0.0)",
    "flickr-url-parser (>=1.11.0,<2.0.0)",
    "redis (>=5.2.1,<6.0.0)",
    "fakeredis (>=2.29.0,<3.0.0)",
]

[tool.poetry]
packages = [{include = "wikibots", from = "src"}]

[tool.poetry.scripts]
flickr = "wikibots.flickr:main"
inaturalist = "wikibots.inaturalist:main"
youtube = "wikibots.youtube:main"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
