[project]
name = "wikibots"
version = "0.1.0"
authors = [
    {name = "DaxServer",email = "daxserver@icloud.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pywikibot (>=10.0.0,<11.0.0)",
    "python-dateutil (>=2.9.0.post0,<3.0.0)",
    "deepdiff (>=8.4.2,<9.0.0)",
    "requests-oauthlib (>=2.0.0,<3.0.0)",
    "google-api-python-client (>=2.166.0,<3.0.0)",
    "lingua-language-detector (>=2.1.0,<3.0.0)",
]

[tool.poetry]
packages = [{include = "wikibots", from = "src"}]

[tool.poetry.scripts]
usace = "wikibots.usace:main"
youtube = "wikibots.youtube:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
