name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-root --with dev

      - name: Run ruff
        run: poetry run ruff check .

      - name: Run isort
        run: poetry run isort --check .
